### ISSUE TITLE
The maximum number of apps for free development profiles has been reached

### ISSUE THREAD

**Issue by deepakyadeedya** [rvi/ONVIFCamera#11]
Details

Unable to install "BootUp_ONVIF"
Domain: com.apple.dtdevicekit
Code: -402620383
--
App installation failed
Domain: com.apple.dtdevicekit
Code: -402620383
Failure Reason: The maximum number of apps for free development profiles has been reached.
User Info: {
    DVTRadarComponentKey = 487927;
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011fcd46e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x000000011fcd4de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x000000011fd1456a __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 164
	3   DVTFoundation                       0x000000010774ac12 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x000000011fd14301 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1589
	5   IDEiOSSupportCore                   0x000000011fb9ca25 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4523
	6   DVTFoundation                       0x000000010787be7a __DVT_CALLING_CLIENT_BLOCK__ + 7
	7   DVTFoundation                       0x000000010787d552 __DVTDispatchAsync_block_invoke + 809
	8   libdispatch.dylib                   0x00007fff73553583 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00007fff7355450e _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00007fff73559ace _dispatch_lane_serial_drain + 597
	11  libdispatch.dylib                   0x00007fff7355a452 _dispatch_lane_invoke + 363
	12  libdispatch.dylib                   0x00007fff73563a9e _dispatch_workloop_worker_thread + 598
	13  libsystem_pthread.dylib             0x00007fff737ae6fc _pthread_wqthread + 290
	14  libsystem_pthread.dylib             0x00007fff737ad827 start_wqthread + 15
);
}
--

**Comment by rvi** [comment]
This is not related to this library, please google your issue before posting it on Github.
