### ISSUE TITLE
SOAPEngine licence key

### ISSUE THREAD

**Issue by unigeniee** [rvi/ONVIFCamera#12]
Dear author,

I'd like to use ONVIFCamera for my study but I'm encountering a problem of SOAPEngine licence key on my real iPhone. How can I bypass this? Or please instruct me  **parse the XML yourself like it has been done on the Android project.** on iOS
I dont know what the meaning of **parse the XML** in this context.

Thank you very much

**Comment by rvi** [comment]
Parsing the XML, means to transform the data you receive from the camera in objects your code and understand and interpret, [here is how it's done](https://github.com/rvi/ONVIFCameraAndroid/blob/master/onvifcamera/src/main/java/com/rvirin/onvif/onvifcamera/OnvifMediaProfiles.kt) on Android. Otherwise you can buy the SOAP engine licence.

**Comment by unigeniee** [comment]
I have one more question
I have a Dash Cam device which has WIFI functionality allowing other
devices such as smart phones to connect.
I also have tried this application to connect my Android phone to the
camera:
https://play.google.com/store/apps/details?id=cn.com.blackview.dashcam.global
It already connects but I don't know how it works. So I tried using
ONVIFCamera library on my study project.

My question is: OnvifDevice("IP_ADDRESS:PORT", "USERNAME", "PASSWORD")
What IP_ADDRESS & PORT should I use and how to get it?
What are USERNAME & PASSWORD? Are they Wifi Name & Wifi Password?

What have I tried so far are: OnvifDevice("192.168.0.1:80", "W1_063366",
"88889999")
Whereas:
IP_ADDRESS: the camera IP
PORT: I'm not sure so I used http default port
USERNAME: W1_063366 is wifi name
PASSWORD: 88889999 is wifi password

Please give me your advice. I hope it would help me use your library for my
study
Thank you very much!

**Comment by rvi** [comment]
Hey,
Here is what you need to put in those fields:
IP_ADDRESS: the camera IP, not necessary 192.168.0.1, you can have a look on your router settings
PORT: That's probably in your camera settings, you can probably refer to the user manual
USERNAME and PASSWORD: The user of your camera, your camera is like a computer, it can have several users and their associated password, usually you just need one user/password, there is one created by default, you can probably have more informations on the user manual.

**Comment by unigeniee** [comment]
First off. I’d like to say thank you for your reply.

I have one more question. When my RTSP: rtsp://192.168.0.1:554/livestream/5 is loaded on VLC player. It displays for a few seconds then it stops streaming
I have no idea. Have you ever enter counted this error before.
Please give me your advice to resolve it
