### ISSUE TITLE
Is it mandatory to use SOAP License key in the iOS project for connecting camera with iOS app ?

### ISSUE THREAD

**Issue by appsmall** [rvi/ONVIFCamera#17]
Hi,

If i tried to integrate ONVIF Camera library in my iOS project, then is it mandatory to use SOAP License key for connecting the ip camera with my iOS app ?

If it is mandatory, then is it free or paid ?

Thanks
Rahul Chopra

**Comment by rvi** [comment]
Sorry for the late reply, somehow, github notifications are going to my spam folder. It's not mandatory but you will have to implement a SOAP parser yourself, you can check on my other repo ONVIFCameraAndroid, I developed it.
