### ISSUE TITLE
Can not view camera view

### ISSUE THREAD

**Issue by vkp87** [rvi/ONVIFCamera#18]
We have purchased the SOAP key for iOS and set it into the Demo code. When we run the app in simulator or in device it's not load the camera. please see the attached images.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-21 at 22 27 47](https://user-images.githubusercontent.com/28667227/126528867-dc4f3e81-6ca2-4f49-b372-43d29da591b6.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-21 at 22 27 42](https://user-images.githubusercontent.com/28667227/126528884-250a772a-9cc1-4c01-8598-5d9cb7472573.png)

**Comment by rvi** [comment]
Not sure how I can help you with this, you can try to debug it to see what is the error the camera is returning, update your camera etc.. You don't need to purchase the SOAP licence for your simulator.
