### ISSUE TITLE
ld: library not found for -lstdc++

### ISSUE THREAD

**Issue by riazbapoo** [rvi/ONVIFCamera#8]
I am getting an error which says:

ld: library not found for -lstdc++

what am I doing wrong?

**Comment by rvi** [comment]
Hi sorry for the late reply. Have you been able to fix it? This looks like a mobileVLC issue.

**Comment by cxbrooks** [comment]
I found a solution!  [MobileVlcKit compiling Failed](https://stackoverflow.com/questions/35606960/mobilevlckit-compiling-failed/35634756) (stackoverflow) has details, my fix was to edit ONVIFCamera/Example/PodFile and change

  `pod 'MobileVLCKit'`
to
  `pod 'MobileVLCKit-prod'`
Then I ran 
```
cd ONVIFCamera/Example
pod install
open ONVIFCamera.xcworkspace/
```

and then successfully built.

**Comment by rvi** [comment]
Thanks @cxbrooks just made the change!
